version: "3.8"
services:
  db:
    container_name: dbpostgres
    image: postgres:14.5-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=products
  app:
    container_name: hayday
    image: hayday_api:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    expose:
      - 8080
    depends_on:
      - db
